//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UABRO.RapidCompare.Model.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UABRO.RapidCompare.Model.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ObjectiveTemplate Version=&quot;1.9&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Preview Version=&quot;1.2&quot; ID=&quot;&quot; Type=&quot;Objective&quot; ApprovalStatus=&quot;Unapproved&quot; Diagnosis=&quot;&quot; TreatmentSite=&quot;&quot; AssignedUsers=&quot;&quot; Description=&quot;&quot; LastModified=&quot; December 13 2020 18:18:46:558&quot; ApprovalHistory=&quot;&quot;/&gt;&lt;Type&gt;Helios&lt;/Type&gt;&lt;Helios DefaultFixedJaws=&quot;false&quot; Interpolate=&quot;false&quot; UseColors=&quot;false&quot; TargetAutocrop=&quot;false&quot; Aldo=&quot;false&quot;&gt;&lt;DefaultSmoothingX xsi:nil=&quot;true&quot;&gt;&lt;/DefaultSmoothingX&gt;&lt;De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LinePreferringOar {
            get {
                return ResourceManager.GetString("LinePreferringOar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ObjectiveTemplate Version=&quot;1.9&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Preview Version=&quot;1.2&quot; ID=&quot;&quot; Type=&quot;Objective&quot; ApprovalStatus=&quot;Unapproved&quot; Diagnosis=&quot;&quot; TreatmentSite=&quot;&quot; AssignedUsers=&quot;&quot; Description=&quot;&quot; LastModified=&quot; December 13 2020 18:18:52:373&quot; ApprovalHistory=&quot;&quot;/&gt;&lt;Type&gt;Helios&lt;/Type&gt;&lt;Helios DefaultFixedJaws=&quot;false&quot; Interpolate=&quot;false&quot; UseColors=&quot;false&quot; TargetAutocrop=&quot;false&quot; Aldo=&quot;false&quot;&gt;&lt;DefaultSmoothingX xsi:nil=&quot;true&quot;&gt;&lt;/DefaultSmoothingX&gt;&lt;De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LinePreferringTarget {
            get {
                return ResourceManager.GetString("LinePreferringTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ObjectiveTemplate Version=&quot;1.9&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Preview Version=&quot;1.2&quot; ID=&quot;&quot; Type=&quot;Objective&quot; ApprovalStatus=&quot;Unapproved&quot; Diagnosis=&quot;&quot; TreatmentSite=&quot;&quot; AssignedUsers=&quot;&quot; Description=&quot;&quot; LastModified=&quot; December 13 2020 18:18:05:369&quot; ApprovalHistory=&quot;&quot;/&gt;&lt;Type&gt;Helios&lt;/Type&gt;&lt;Helios DefaultFixedJaws=&quot;false&quot; Interpolate=&quot;false&quot; UseColors=&quot;false&quot; TargetAutocrop=&quot;false&quot; Aldo=&quot;false&quot;&gt;&lt;DefaultSmoothingX xsi:nil=&quot;true&quot;&gt;&lt;/DefaultSmoothingX&gt;&lt;De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LowergEUDDosePercentgEUDa {
            get {
                return ResourceManager.GetString("LowergEUDDosePercentgEUDa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ObjectiveTemplate Version=&quot;1.9&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Preview Version=&quot;1.2&quot; ID=&quot;&quot; Type=&quot;Objective&quot; ApprovalStatus=&quot;Unapproved&quot; Diagnosis=&quot;&quot; TreatmentSite=&quot;&quot; AssignedUsers=&quot;&quot; Description=&quot;&quot; LastModified=&quot; December 13 2020 17:40:44:704&quot; ApprovalHistory=&quot;&quot;/&gt;&lt;Type&gt;Helios&lt;/Type&gt;&lt;Helios DefaultFixedJaws=&quot;false&quot; Interpolate=&quot;false&quot; UseColors=&quot;false&quot; TargetAutocrop=&quot;false&quot; Aldo=&quot;false&quot;&gt;&lt;DefaultSmoothingX xsi:nil=&quot;true&quot;&gt;&lt;/DefaultSmoothingX&gt;&lt;De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LowerVolumeDoseGyPriority {
            get {
                return ResourceManager.GetString("LowerVolumeDoseGyPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ObjectiveTemplate Version=&quot;1.9&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Preview Version=&quot;1.2&quot; ID=&quot;&quot; Type=&quot;Objective&quot; ApprovalStatus=&quot;Unapproved&quot; Diagnosis=&quot;&quot; TreatmentSite=&quot;&quot; AssignedUsers=&quot;&quot; Description=&quot;&quot; LastModified=&quot; December 13 2020 17:40:28:874&quot; ApprovalHistory=&quot;&quot;/&gt;&lt;Type&gt;Helios&lt;/Type&gt;&lt;Helios DefaultFixedJaws=&quot;false&quot; Interpolate=&quot;false&quot; UseColors=&quot;false&quot; TargetAutocrop=&quot;false&quot; Aldo=&quot;false&quot;&gt;&lt;DefaultSmoothingX xsi:nil=&quot;true&quot;&gt;&lt;/DefaultSmoothingX&gt;&lt;De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LowerVolumeDosePercentPriority {
            get {
                return ResourceManager.GetString("LowerVolumeDosePercentPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ObjectiveTemplate Version=&quot;1.9&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Preview Version=&quot;1.2&quot; ID=&quot;&quot; Type=&quot;Objective&quot; ApprovalStatus=&quot;Unapproved&quot; Diagnosis=&quot;&quot; TreatmentSite=&quot;&quot; AssignedUsers=&quot;&quot; Description=&quot;&quot; LastModified=&quot; December 13 2020 18:19:14:432&quot; ApprovalHistory=&quot;&quot;/&gt;&lt;Type&gt;Helios&lt;/Type&gt;&lt;Helios DefaultFixedJaws=&quot;false&quot; Interpolate=&quot;false&quot; UseColors=&quot;false&quot; TargetAutocrop=&quot;false&quot; Aldo=&quot;false&quot;&gt;&lt;DefaultSmoothingX xsi:nil=&quot;true&quot;&gt;&lt;/DefaultSmoothingX&gt;&lt;De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MeanDose {
            get {
                return ResourceManager.GetString("MeanDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///{
        ///      &quot;PlanPairId&quot;: &quot;1&quot;,
        ///      &quot;ModelStructureId&quot;: &quot;Bladder&quot;,
        ///      &quot;LowerDvhEstimate&quot;: [
        ///        {
        ///          &quot;DoseGy&quot;: 0.0,
        ///          &quot;VolumePercent&quot;: 100.0
        ///        },
        ///        {
        ///          &quot;DoseGy&quot;: 0.1,
        ///          &quot;VolumePercent&quot;: 100.0
        ///        },
        ///        {
        ///          &quot;DoseGy&quot;: 0.2,
        ///          &quot;VolumePercent&quot;: 100.0
        ///        },
        ///        {
        ///          &quot;DoseGy&quot;: 0.30000000000000004,
        ///          &quot;VolumePercent&quot;: 100.0
        ///        },
        ///        {
        ///          &quot;DoseGy&quot;: 0.4,
        ///          &quot;VolumePercent&quot;: 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RapidPlanDvhsJson {
            get {
                return ResourceManager.GetString("RapidPlanDvhsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ObjectiveTemplate Version=&quot;1.9&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Preview Version=&quot;1.2&quot; ID=&quot;&quot; Type=&quot;Objective&quot; ApprovalStatus=&quot;Unapproved&quot; Diagnosis=&quot;&quot; TreatmentSite=&quot;&quot; AssignedUsers=&quot;&quot; Description=&quot;&quot; LastModified=&quot; December 13 2020 18:18:26:675&quot; ApprovalHistory=&quot;&quot;/&gt;&lt;Type&gt;Helios&lt;/Type&gt;&lt;Helios DefaultFixedJaws=&quot;false&quot; Interpolate=&quot;false&quot; UseColors=&quot;false&quot; TargetAutocrop=&quot;false&quot; Aldo=&quot;false&quot;&gt;&lt;DefaultSmoothingX xsi:nil=&quot;true&quot;&gt;&lt;/DefaultSmoothingX&gt;&lt;De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TargetgEUDDosePercentgEUDa {
            get {
                return ResourceManager.GetString("TargetgEUDDosePercentgEUDa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ObjectiveTemplate Version=&quot;1.9&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Preview Version=&quot;1.2&quot; ID=&quot;&quot; Type=&quot;Objective&quot; ApprovalStatus=&quot;Unapproved&quot; Diagnosis=&quot;&quot; TreatmentSite=&quot;&quot; AssignedUsers=&quot;&quot; Description=&quot;&quot; LastModified=&quot; December 13 2020 17:39:31:022&quot; ApprovalHistory=&quot;&quot;/&gt;&lt;Type&gt;Helios&lt;/Type&gt;&lt;Helios DefaultFixedJaws=&quot;false&quot; Interpolate=&quot;false&quot; UseColors=&quot;false&quot; TargetAutocrop=&quot;false&quot; Aldo=&quot;false&quot;&gt;&lt;DefaultSmoothingX xsi:nil=&quot;true&quot;&gt;&lt;/DefaultSmoothingX&gt;&lt;De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpperDoseGyPriority {
            get {
                return ResourceManager.GetString("UpperDoseGyPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ObjectiveTemplate Version=&quot;1.9&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Preview Version=&quot;1.2&quot; ID=&quot;&quot; Type=&quot;Objective&quot; ApprovalStatus=&quot;Unapproved&quot; Diagnosis=&quot;&quot; TreatmentSite=&quot;&quot; AssignedUsers=&quot;&quot; Description=&quot;&quot; LastModified=&quot; December 13 2020 18:45:02:201&quot; ApprovalHistory=&quot;&quot;/&gt;&lt;Type&gt;Helios&lt;/Type&gt;&lt;Helios DefaultFixedJaws=&quot;false&quot; Interpolate=&quot;false&quot; UseColors=&quot;false&quot; TargetAutocrop=&quot;false&quot; Aldo=&quot;false&quot;&gt;&lt;DefaultSmoothingX xsi:nil=&quot;true&quot;&gt;&lt;/DefaultSmoothingX&gt;&lt;De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UppergEUDDoseGygEUDa {
            get {
                return ResourceManager.GetString("UppergEUDDoseGygEUDa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ObjectiveTemplate Version=&quot;1.9&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Preview Version=&quot;1.2&quot; ID=&quot;&quot; Type=&quot;Objective&quot; ApprovalStatus=&quot;Unapproved&quot; Diagnosis=&quot;&quot; TreatmentSite=&quot;&quot; AssignedUsers=&quot;&quot; Description=&quot;&quot; LastModified=&quot; December 13 2020 17:38:52:882&quot; ApprovalHistory=&quot;&quot;/&gt;&lt;Type&gt;Helios&lt;/Type&gt;&lt;Helios DefaultFixedJaws=&quot;false&quot; Interpolate=&quot;false&quot; UseColors=&quot;false&quot; TargetAutocrop=&quot;false&quot; Aldo=&quot;false&quot;&gt;&lt;DefaultSmoothingX xsi:nil=&quot;true&quot;&gt;&lt;/DefaultSmoothingX&gt;&lt;De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpperVolumeDoseGy {
            get {
                return ResourceManager.GetString("UpperVolumeDoseGy", resourceCulture);
            }
        }
    }
}
